repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: git://github.com/carterjones/pre-commit-golang
    rev: ac63cdce000b849f008d20ed1fc611cbccb40c5b
    hooks:
    -   id: go-fmt
    -   id: go-vet
    -   id: go-lint
    -   id: go-build
    -   id: go-metalinter
        args:
        - --vendor
        - --cyclo-over=12
        - --enable=nakedret
